CREATE TABLE events (
    _id INTEGER PRIMARY KEY AUTO_INCREMENT,
    _created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    _updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    _status VARCHAR(100) DEFAULT 'active',
    id VARCHAR(100) NOT NULL,
    title TEXT NOT NULL,
    note TEXT,
    created_at TIMESTAMP NOT NULL,
    type_id INTEGER
);

CREATE TABLE event_types (
    _id INTEGER PRIMARY KEY AUTO_INCREMENT,
    _created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    _updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    _status VARCHAR(100) DEFAULT 'active',
    value TEXT
);

CREATE TABLE event_tags (
    _id INTEGER PRIMARY KEY AUTO_INCREMENT,
    _created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    _updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    _status VARCHAR(100) DEFAULT 'active',
    value TEXT
);

CREATE TABLE event_tag_mappings (
    _id INTEGER PRIMARY KEY AUTO_INCREMENT,
    _created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    _updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    _status VARCHAR(100) DEFAULT 'active',
    event_id INTEGER,
    tag_id INTEGER
);

ALTER TABLE events
ADD CONSTRAINT fk_type_id FOREIGN KEY(type_id) REFERENCES event_types(_id);

ALTER TABLE event_tag_mappings
ADD CONSTRAINT fk_event_id FOREIGN KEY(event_id) REFERENCES events(_id);

ALTER TABLE event_tag_mappings
ADD CONSTRAINT fk_tag_id FOREIGN KEY(tag_id) REFERENCES event_tags(_id);

INSERT INTO event_types (value) VALUES
('start'),
('end'),
('single');
