ALTER TABLE events
MODIFY COLUMN created_at TIMESTAMP NOT NULL,
MODIFY COLUMN _created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
MODIFY COLUMN _updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE event_types
MODIFY COLUMN _created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
MODIFY COLUMN _updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE event_tags
MODIFY COLUMN _created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
MODIFY COLUMN _updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE event_tag_mappings
MODIFY COLUMN _created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
MODIFY COLUMN _updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
