ALTER TABLE events
MODIFY COLUMN created_at DATETIME(6) NOT NULL,
MODIFY COLUMN _created_at DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
MODIFY COLUMN _updated_at DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6);

ALTER TABLE event_types
MODIFY COLUMN _created_at DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
MODIFY COLUMN _updated_at DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6);

ALTER TABLE event_tags
MODIFY COLUMN _created_at DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
MODIFY COLUMN _updated_at DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6);

ALTER TABLE event_tag_mappings
MODIFY COLUMN _created_at DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
MODIFY COLUMN _updated_at DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6);
